project:
  type: website
  render:
    - "*.qmd"
  post-render: quarto/scripts/restoreMarkdownToHeirarchy.sh
  #resources:

website:
  title: "Foundational Python for Data Science: Notes"
  page-navigation: true
  open-graph: true
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true
    contents:
      - section: "I: Learning Python in a Notebook Environment"
        contents:
          - 1-learning-python-in-a-notebook-environment/Chapter_01/Chapter_01.qmd
          - 1-learning-python-in-a-notebook-environment/Chapter_02/Chapter_02.qmd
          - 1-learning-python-in-a-notebook-environment/Chapter_03/Chapter_03.qmd
          - 1-learning-python-in-a-notebook-environment/Chapter_04/Chapter_04.qmd
          - 1-learning-python-in-a-notebook-environment/Chapter_05/Chapter_05.qmd
          - 1-learning-python-in-a-notebook-environment/Chapter_06/Chapter_06.qmd
      - section: "II: Data Science Libraries"
        contents:
          - 2-data-science-libraries/Chapter_07/Chapter_07.qmd
          - 2-data-science-libraries/Chapter_08/Chapter_08.qmd
          - 2-data-science-libraries/Chapter_09/Chapter_09.qmd
          - 2-data-science-libraries/Chapter_10/Chapter_10.qmd
          - 2-data-science-libraries/Chapter_11/Chapter_11.qmd
          - 2-data-science-libraries/Chapter_12/Chapter_12.qmd
      - section: "III: Intermediate Python"
        contents:
          - 3-intermediate-python/Chapter_13/Chapter_13.qmd
          - 3-intermediate-python/Chapter_14/Chapter_14.qmd
          - 3-intermediate-python/Chapter_15/Chapter_15.qmd

format:
  html:
    code-fold: false
    code-links:
      - repo
      - binder
  gfm:
    filters:
      - quarto/scripts/strip_ansi.lua
  ipynb: default
toc: true
toc-depth: 6
format-links: false
execute:
  enabled: true
  error: true
engine: jupyter
