---
title: "Chapter 8: SciPy"
---

## Notes

### SciPy Overview

- SciPy is a package that builds on [NumPy](../Chapter_07/Chapter_07.qmd) to enable scientific computing
- Provides specialised submodules for different functionality, including,
    - Optimisation
    - Fourier Transformations
    - Signal Processing
    - Linear Algebra
    - Image Processing
    - Statistics
    - and more...
- SciPy and NumPy are often paired with MatplotLib for visualisation
- Unlike `NumPy` there is no accepted shorthand for importing however `import scipy as sp` is used fairly often in practice

### The `scipy.misc` Submodule

- Contains functions that don't below in a more broader submodule
- Some of these are just special demo functions
    - For example, `face` and `ascent`
    - These now live in the `scipy.datasets`
    - Require the optional `pooch` package

:::{.callout-important}
**`misc` Deprecation**

Scipy has deprecated `misc` and it is planned for removal in Scipy 2.0. All the functionality of `misc` has been removed. For example the `face` and `ascent` functions now live in `scipy.datasets`
:::

```{python}
from scipy import datasets
import matplotlib.pyplot as plt

face = datasets.face()
print(face)

plt.imshow(face)
plt.show()
```

- And doing the same for `ascent`

```{python}
from scipy import datasets
import matplotlib.pyplot as plt

ascent = datasets.ascent()
print(a)

plt.imshow(a)
plt.show()
```

- `face` and `ascent` return NumPy arrays representing an image.
- The `imshow` function from `matplotlib.pyplot` can be used to plot an image


### The `scipy.special` Submodule

- `scipy.special` contains special functions commonly used in mathematical physics, including
    - Airy functions,
    - Bessel functions,
    - Elliptical functions,
    - Struve functions,
    - and more
- These functions are designed to operate with NumPy arrays
    - Support broadcasting
- For example,

```{python}
from scipy import special

print("special.factorial(3):", special.factorial(3))
print("Combinations:", special.comb(10, 2))
print("Permutations:", special.perm(10, 2))
```

:::{.callout-caution}
**`scipy.special.stats` vs `scipy.stats`**

`scipy.special` contains a `stats` submodule. This is not designed for direct use. Instead the `scipy.stats` module should be preferred
:::

### The `scipy.stats` Submodule

- Provides probability distributions and statistical functions

#### Discrete Distributions

- Scipy offers several discrete distributions
- Each provides a common interface
- For example, demonstrating with a binomial distribution

```{python}
from scipy import stats
import matplotlib.pyplot as plt

B = stats.binom(20, 0.3)  # 20 trials with a 30% success chance

print("B.pmf(2):", B.pmf(2)) # Probability mass function P(x == 2)

print("B.cdf(4):", C.cdf(4)) # Cumulative density function (P x < 4)

print("B.mean():", B.mean()) # Mean

print("B.std():", B.std()) # Std-dev

print("B.rvs():", B.rvs()) # Get a random sample from the distribution

print("B.rvs(15):", B.rvs(15)) # Get 15 random samples from the distribution

# Plotting a large sampling of the distribution
samples = B.rvs(size=100_000)
plt.hist(samples)
plt.show()
```

- Another discrete distribution is the Poisson Distribution
    - Models the probability of a certain number of events happening
    - Shape of the distribution is controlled by the mean
        - Set via the `mu` keyword
        - A low mean skews the distribution left
        - A high mean pushes the distribution right

- A left-skewed distribution
```{python}
from scipy import stats
import matplotlib.pyplot as plt

P = stats.poisson(mu=3)
samples = P.rvs(size=10_000)
plt.hist(samples)
plt.show()
```

- A right-shifted distribution

```{python}
from scipy import stats
import matplotlib.pyplot as plt

P = stats.poisson(mu=15)
samples = P.rvs(size=10_000)
plt.hist(samples)
plt.show()
```

- There are number of further discrete distributions provided by `scipy.stats` including,
    - Beta-binomial,
    - Boltzmann (Truncated Planck),
    - Planck (Discrete Exponential),
    - Geometric,
    - Hyper-geometric,
    - Logarithmic,
    - Yule-Simon,
    - and more

#### Continuous Distributions

- Scipy also supports continuous distributions
    - There are more continuous distributions supported than there are discrete
- Like discrete distributions they all have a common interface
    - Take arguments for *location* (`loc`) and *scale* (`scale`)
        - By default, the location is $0$ and the scale is $1$

- For example, a common continuous distribution is the normal distribution

```{python}
from scipy import stats
import matplotlib.pyplot as plt

N = stats.norm() # a Normal Distribution located at `0` and with scale `1`
samples = N.rvs(size=100_000)
plt.hist(rvs, bins=1000)
plt.show()
```

- As we change the `loc` and `scale` parameters the distribution will change too

```{python}
from scipy import stats
import matplotlib.pyplot as plt

N = stats.norm(loc=30, scale=50)
samples = N.rvs(size=100_000)
plt.hist(rvs, bins=100)
plt.show()
```

- As mentioned continuous distributions have a common interface

```{python}
from scipy import stats

N = stats.norm(loc=30, scale=50)

print("N.mean():", N.mean())

print("N.pdf(4):", N.pdf(4)) # Probability Density Function

print("N.cdf(2):", N.cdf(2)) # Cumulative density function

print("N.rvs():", N.rvs()) # Random sample from the distribution

print("N.var():", N.var()) # Variance

print("N.median():", N.median()) # Median

print("N.std():", N.std()) # Standard Deviation
```

- A continuous analogue to the Poisson Distribution is the exponential distribution

```{python}
from scipy import stats
import matplotlib.pyplot as plt

E = stats.expon()
samples = E.rvs(size=100_000)
plt.hist(samples, bins=1_000)
plt.show()
```

- We can also use a uniform distribution

```{python}
from scipy import stats
import matplotlib.pyplot as plt

U = stats.uniform()
samples = E.rvs(size=100_000)
plt.hist(samples)
plt.show()
```

## Summary

- Scipy extend NumPy with specialised functionality for complex scientific computing

## Questions

1. Use the `scipy.stats` module to model a Normal distribution with a mean of 15

   ```python
    from scipy import stats

    U = stats.normal(location=15)
   ```

2. Generate $25$ random samples from the distribution modelled in Question 1

   ```python
    from scipy import stats

    U = stats.normal(location=15)
    samples = U.rvs(25)
   ```

3. Which SciPy module has utilities designed for mathematical physics?

   - Special functions like those used in mathematical physics are stored in `scipy.special`

4. What method is provided with a discrete distribution to calculate it standard deviation?

   - The standard deviation can be found with the `.std` method

See answers implemented below

```{python}
from scipy import stats
import matplotlib.pyplot as plt

U = stats.normal(location=15)
print("Q1\nU.mean() =": U.mean())

print("Q2")
samples = U.rvs(25)
print(samples)
plt.imshow(samples)
plt.show()

print("Q4")
V = stats.binomial(20, 0.3)
print("Standard Deviation:", V.std())
```
